version: 2
updates:
  - package-ecosystem: "npm"
    # location of `package-lock.json`
    directory: "/Source/Builder/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"