name: Bogus CI/CD Pipeline

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump release version and create release tag
        id: tag_generator
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          default_bump: false

      # - name: Initialize CodeQL
      #   id: init_codeql
      #   uses: github/codeql-action/init@v1

      # - name: Cache SonarCloud packages
      #   id: cache_sonar_packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~\sonar\cache
      #     key: ${{ runner.os }}-sonar
      #     restore-keys: ${{ runner.os }}-sonar

      # - name: Cache SonarCloud scanner
      #   id: cache_sonar_scanner
      #   uses: actions/cache@v1
      #   with:
      #     path: .\.sonar\scanner
      #     key: ${{ runner.os }}-sonar-scanner
      #     restore-keys: ${{ runner.os }}-sonar-scanner

      # - name: Install SonarCloud scanner
      #   id: install_sonar_scanner
      #   if: steps.cache_sonar_scanner.outputs.cache-hit != 'true'
      #   shell: powershell
      #   run: |
      #     New-Item -Path .\.sonar\scanner -ItemType Directory
      #     dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # - name: Initialize SonarCloud scanner
      #   id: init_sonar_scanner
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   shell: powershell
      #   run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"szlatkow_Bogus" /o:"szlatkow" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore dotnet tools
        id: restore_dotnet
        run: dotnet tool restore

      - name: Build project
        id: build_project
        run: dotnet fake run Source\Builder\build.fsx target ci
        env:
          FORCE_VERSION: ${{ steps.tag_generator.outputs.new_version }}

      # - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      - name: Upload package artifact
        id: up_package_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: __package/

      # - name: Run project tests
      #   id: run_project_tests
      #   run: dotnet fake run Source\Builder\build.fsx target test

      # - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   name: Upload build test results artifact
      #   id: up_build_test_results_artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: TestResults
      #     path: __test/

      # - name: Perform CodeQL Analysis
      #   id: codeql_analysis
      #   uses: github/codeql-action/analyze@v1

      # - name: Send SonarCloud results
      #   id: send_sonar_results
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      #   run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: 'Event trigger testing:'
        run: |
          echo 'Event: Check run = ' ${{ github.event_name == 'check_run' }}
          echo 'Event: Check suite = ' ${{ github.event_name == 'check_suite' }}
          echo 'Event: Create = ' ${{ github.event_name == 'create' }}
          echo 'Event: Delete = ' ${{ github.event_name == 'delete' }}
          echo 'Event: Deployment = ' ${{ github.event_name == 'deployment' }}
          echo 'Event: Deployment status = ' ${{ github.event_name == 'deployment_status' }}
          echo 'Event: Fork = ' ${{ github.event_name == 'fork' }}
          echo 'Event: Gollum (Wiki page update) = ' ${{ github.event_name == 'gollum' }}
          echo 'Event: Issue comment = ' ${{ github.event_name == 'issue_comment' }}
          echo 'Event: Issues = ' ${{ github.event_name == 'issues' }}
          echo 'Event: Label = ' ${{ github.event_name == 'label' }}
          echo 'Event: Milestone = ' ${{ github.event_name == 'milestone' }}
          echo 'Event: Page build = ' ${{ github.event_name == 'page_build' }}
          echo 'Event: Project = ' ${{ github.event_name == 'project' }}
          echo 'Event: Project card = ' ${{ github.event_name == 'project_card' }}
          echo 'Event: Project column = ' ${{ github.event_name == 'project_column' }}
          echo 'Event: Public = ' ${{ github.event_name == 'public' }}
          echo 'Event: Pull request = ' ${{ github.event_name == 'pull_request' }}
          echo 'Event: Pull request review = ' ${{ github.event_name == 'pull_request_review' }}
          echo 'Event: Pull request review comment = ' ${{ github.event_name == 'pull_request_review_comment' }}
          echo 'Event: Pull request target = ' ${{ github.event_name == 'pull_request_target' }}
          echo 'Event: Push = ' ${{ github.event_name == 'push' }}
          echo 'Event: Registry package = ' ${{ github.event_name == 'registry_package' }}
          echo 'Event: Release = ' ${{ github.event_name == 'release' }}
          echo 'Event: Status = ' ${{ github.event_name == 'status' }}
          echo 'Event: Watch = ' ${{ github.event_name == 'watch' }}
          echo 'Event: Workflow run = ' ${{ github.event_name == 'workflow_run' }}

      - name: 'Which branch is the push to:'
        run: echo ${{ github.ref }}

      - name: 'Is there a tag ?'
        run: echo 'This is the tag = ' ${{ steps.tag_generator.outputs.new_version == '' }}         

  cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: ci
    runs-on: windows-latest
    steps:      
      - name: Download and extract package artifact
        id: dl_package_artifact
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: __package/

      # - name: Download build test results artifact
      #   id: dl_build_test_results_artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: TestResults
      #     path: __test/          

      # - name: Publish *.nupkg on NuGet
      #   id: publish_nuget
      #   uses: rohith/publish-nuget@v2
      #   continue-on-error: true
      #   with:
      #       PROJECT_FILE_PATH: 'Source/Bogus/Bogus.csproj'
      #       TAG_COMMIT: true
      #       NUGET_KEY: ${{secrets.API_KEY}}
      #       PACKAGE_NAME: Fake-package-01

      - name: Create and publish release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_generator.outputs.new_tag }}
          release_name: Release ${{ steps.tag_generator.outputs.new_tag }}
          body: "[CHANGE LOG](HISTORY.md)"


      - name: Upload Bogus.zip as release asset
        id: upload_bogus_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.zip
          asset_name: Bogus.zip
          asset_content_type: application/zip

      - name: Upload Bogus.nupkg as release asset
        id: upload_bogus_snupkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.${{ steps.tag_generator.outputs.new_version }}.snupkg
          asset_name: Bogus.${{ steps.tag_generator.outputs.new_version }}.snupkg
          asset_content_type: application/snupkg

      - name: Upload Bogus.snupkg as release asset
        id: upload_bogus_nupkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: __package/Bogus.${{ steps.tag_generator.outputs.new_version }}.nupkg
          asset_name: Bogus.${{ steps.tag_generator.outputs.new_version }}.nupkg
          asset_content_type: application/nupkg

      # - name: Upload internal test results as release asset
      #   id: upload_internal_test_results
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: __test/results.xml
      #     asset_name: results.xml
      #     asset_content_type: application/xml